# Uncomment the next line to define a global platform for your project
 platform :ios, '13.2'

target 'CloudPhotosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CloudPhotosApp

  target 'CloudPhotosAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CloudPhotosAppUITests' do
  # Pods for testing
  end

  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods



end
